In [1]:
import numpy as np

In [2]:
#Exercise 1: Create a 4X2 integer array and Prints its attributes

arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [3]:
#Exercise 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
arr = np.arange(100,200,10).reshape(5,2)
arr

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [4]:
#Exercise 3: Following is the provided numPy array. Return array of items by taking the third column from all rows
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray[:,-1]

array([33, 66, 99])

In [5]:
#Exercise 4: Return array of odd rows and even columns from below numpy array
arr = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
arr

newarr = arr[0::2,1::2]
newarr

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [7]:
#Exercise 5: Create a result array by adding the following two NumPy arrays. 
#Next, modify the result array by calculating the square of each element

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [9]:
newarr = arrayOne+arrayTwo
newarr = newarr**2
newarr

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [15]:
for i in np.nditer(newarr):
    print(i)

400
1521
1089
625
625
784


In [62]:
#Exercise 6: Split the array into four equal-sized sub-arrays
#Create an 8X3 integer array from a range between 10 to 34 such
#that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.

arr = np.arange(10,34,1).reshape(8,3)
np.split(arr,4)

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [65]:
#Exercise 7: Sort following NumPy array
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sortArrayByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sortArrayByRow)

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [1]:
#Exercise 8: Print max from axis 0 and min from axis 1 from the following 2-D array.
import numpy as np
arr = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(arr.min(axis=1)[1])

print(arr.max(axis=0)[0])

12
82


In [17]:
#Exercise 9: Delete the second column from a given array and insert the following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])

newarray = np.delete(sampleArray,1,axis=1)
np.insert(newarray,1,newColumn,axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [22]:
#Exercise 9: Delete the second column from a given array and insert the following new column in its place.
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
newColumn = np.array([[10,10,10]])

newarray = np.delete(sampleArray,1,axis=0)
np.insert(newarray,0,newColumn,axis=0)

array([[10, 10, 10],
       [34, 43, 73],
       [53, 94, 66]])

In [80]:
#Exercise 10: Create two 2-D arrays and Plot them using matplotlib
import numpy

print("Printing Original array")
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = numpy.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = numpy.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = numpy.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


### New Type of Questions

In [6]:
#Exercise 1 - Replace all odd numbers in the given array with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
#Exerciese 2 - Convert a 1-D array into a 2-D array with 3 rows
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
exercise_2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
#Exercise 3 - Add 202 to all the values in given array
exercise_3 = np.arange(4).reshape(2,-1)
exercise_3 + 202

array([[202, 203],
       [204, 205]])

In [46]:
#Exercise 4 - Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive)
arr = np.random.randint(30,41,size=10)
arr

array([30, 40, 36, 31, 34, 31, 31, 31, 32, 39])

In [7]:
#Exercie 5 - Find the positions of:

#elements in x where its value is more than its corresponding element in y, and
#elements in x where its value is equals to its corresponding element in y.
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 86, 45, 10, 29, 55, 4, 37, 18])

temp = []
for i in range(len(x)):
    if x[i]>y[i]:
        temp.append(i)
        
print(temp)
print(np.where(x>30))
print(np.where(x==y))

[1, 4, 5, 6, 7, 8, 9]
(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)
(array([0, 2], dtype=int64),)


In [68]:
#Exercise 6 - Extract the first four columns of this 2-D array
exercise_6 = np.arange(100).reshape(5,-1)
exercise_6[0:,0:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

### 100 Numpy Exercise Questions

In [69]:
#1. Import the numpy package under the name np
import numpy as np

In [71]:
#2. Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.18.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [72]:
#3. Create a null vector of size 10
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
#4. How to get the documentation of the numpy add function from the command line?

In [76]:
#5. Create a null vector of size 10 but the fifth value which is 1
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [11]:
#6. Create a vector with values ranging from 10 to 49
arr = np.arange(10,50,10).reshape(2,2)
print(arr)
arr[::-1]

[[10 20]
 [30 40]]


array([[30, 40],
       [10, 20]])

In [80]:
#7. Reverse a vector (first element becomes last)
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [81]:
#8. Create a 3x3 matrix with values ranging from 0 to 8
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
#9. Find indices of non­zero elements from [1,2,0,0,4,0]

print(np.where(arr<5))

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 1], dtype=int64))


In [97]:
#10. Create a 3x3 identity matrix
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [99]:
#11. Create a 3x3x3 array with random values
z = np.random.random((3,3,3))
z

array([[[0.96816234, 0.8743382 , 0.62426777],
        [0.2313171 , 0.40846505, 0.50163834],
        [0.44636097, 0.17251748, 0.04755433]],

       [[0.21823888, 0.35458936, 0.34879952],
        [0.02782623, 0.55142196, 0.93339892],
        [0.93839321, 0.79925927, 0.58875737]],

       [[0.69658849, 0.80240318, 0.94792907],
        [0.73976961, 0.9945752 , 0.4809197 ],
        [0.33122616, 0.55607685, 0.64986406]]])

In [106]:
#12. Create a 10x10 array with random values and find the minimum and maximum values
arr = np.arange(100).reshape(10,10)
print(arr.min(axis=1))
print(arr.max(axis=1))

[ 0 10 20 30 40 50 60 70 80 90]
[ 9 19 29 39 49 59 69 79 89 99]


In [107]:
#13. Create a random vector of size 30 and find the mean value
arr = np.arange(30)
arr.mean()

14.5

In [118]:
#14. Create a 2d array with 1 on the border and 0 inside
arr = np.zeros(9).reshape(3,3)
arr[0,0] = 1
arr[0,-1]=1
arr[-1,0]=1
arr[-1,-1]=1
arr

array([[1., 0., 1.],
       [0., 0., 0.],
       [1., 0., 1.]])

In [119]:
#15. What is the result of the following expression?
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1


False

In [123]:
#16. Create a 5x5 matrix with values 1,2,3,4 just below the diagona
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [22]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [23]:
#17. Create a 8x8 matrix and fill it with a checkerboard pattern (
arr = np.arange(64).reshape(8,8)

arr[::2,::2]

array([[ 0,  2,  4,  6],
       [16, 18, 20, 22],
       [32, 34, 36, 38],
       [48, 50, 52, 54]])

In [156]:
#18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
arr[np.where(arr>50)]

np.where((arr>=50) & (arr<=60))

(array([6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7], dtype=int64),
 array([2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4], dtype=int64))

In [159]:
#19. Create a checkerboard 8x8 matrix using the tile function 
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [163]:
#20. Normalize a 5x5 random matrix
arr = np.arange(25).reshape(5,5)
print(arr)
arr = arr-arr.min()/(arr.max() - arr.min())
arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [166]:
#22. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(6).reshape(3,2)
arr = np.dot(arr1,arr2)
arr

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [171]:
#23. Given a 1D array, negate all elements which are between 3 and 8, in place
arr = np.arange(9)
arr[np.where((arr>3) & (arr<8))]

array([4, 5, 6, 7])

In [173]:
#24. What is the output of the following script?
# Author: Jake VanderPlas
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
np.sum(arr)


10
10


36

In [177]:
#31. Create a vector of size 10 with values ranging from 0 to 1, both excluded
z = np.linspace(1,10)
z

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [182]:
#32. Create a random vector of size 10 and sort it
arr = np.random.rand(10)
arr.sort()
arr

array([0.09037578, 0.10202906, 0.15183388, 0.15830557, 0.24877677,
       0.28750224, 0.35133212, 0.41954651, 0.74682248, 0.98065573])

In [184]:
#33. How to sum a small array faster than np.sum?
Z = np.arange(10)
np.add.reduce(Z)
np.sum(z)

275.0

In [192]:
#34. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

False

In [193]:
np.sqrt(arr)

array([0.30062565, 0.31941989, 0.38965868, 0.39787632, 0.49877527,
       0.53619236, 0.59273276, 0.6477241 , 0.86418891, 0.99028063])

In [197]:
#37. Create random vector of size 10 and replace the maximum value by 0
arr = np.arange(10)
arr[arr.max()] = 0
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0])

In [199]:
arr = np.arange(10)
arr[arr%2==0] = 0
arr

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

In [202]:
#40. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [5]:
import numpy as np
my_array = np.array([[[[1,3,4]]]])
my_array

array([[[[1, 3, 4]]]])

In [7]:
np.array(my_array, ndmin=5)

array([[[[[1, 3, 4]]]]])

In [10]:
Array1 = np.array([[1, 2, 3], [4, 5, 6]]) 
Array2 = np.array([[2, 3],[3, 2]])

In [12]:
np.dot(Array1,Array2)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [13]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]] 
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [14]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [16]:
a = np.array([3, 7, 32], dtype = complex)
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [17]:
array1 = np.array([[1,2],[3,4]])
array1

array([[1, 2],
       [3, 4]])

In [22]:
array = np.array([10,3,1,203,404,204,20,302,30,402,192])  
array2 = [1,2,3,4]
np.insert(array1, 4, array2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [26]:
np.full((3,3), 'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [30]:
def bub_sort(array):
    for i in range(0, len(array)):
        for j in range(0, len(array) - i - 1):
            if array[j] < array[j + 1]:
                temp = array[j]
                array[j] = array[j + 1]
                array[j+1] = temp
                return array
            my_array = np.array([20,14,25,16,45,60,12,9])

In [31]:
my_array

array([[[[1, 3, 4]]]])

In [40]:
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
Sample[0:3,1]

array([2, 5, 8])

In [38]:
Sample

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [42]:
A = np.array([[4],[12],[29]])
B = np.array([[13],[21],[4]])

In [43]:
np.cross(a,b)

array([[[[-8957.+0.j, 10417.+0.j, -1439.+0.j],
         [-8882.+0.j, 10330.+0.j, -1427.+0.j],
         [-8807.+0.j, 10243.+0.j, -1415.+0.j],
         [-8732.+0.j, 10156.+0.j, -1403.+0.j],
         [-8657.+0.j, 10069.+0.j, -1391.+0.j],
         [-8582.+0.j,  9982.+0.j, -1379.+0.j]],

        [[-8507.+0.j,  9895.+0.j, -1367.+0.j],
         [-8432.+0.j,  9808.+0.j, -1355.+0.j],
         [-8357.+0.j,  9721.+0.j, -1343.+0.j],
         [-8282.+0.j,  9634.+0.j, -1331.+0.j],
         [-8207.+0.j,  9547.+0.j, -1319.+0.j],
         [-8132.+0.j,  9460.+0.j, -1307.+0.j]],

        [[-8057.+0.j,  9373.+0.j, -1295.+0.j],
         [-7982.+0.j,  9286.+0.j, -1283.+0.j],
         [-7907.+0.j,  9199.+0.j, -1271.+0.j],
         [-7832.+0.j,  9112.+0.j, -1259.+0.j],
         [-7757.+0.j,  9025.+0.j, -1247.+0.j],
         [-7682.+0.j,  8938.+0.j, -1235.+0.j]],

        [[-7607.+0.j,  8851.+0.j, -1223.+0.j],
         [-7532.+0.j,  8764.+0.j, -1211.+0.j],
         [-7457.+0.j,  8677.+0.j, -1199.+0.j],
       

In [45]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])

my_rho = np.corrcoef(A, B)

print(my_rho)

[[1. 1.]
 [1. 1.]]


In [46]:
arr1= np.array([[3,2,1],[6,4,5],[8,7,9]])
arr1

array([[3, 2, 1],
       [6, 4, 5],
       [8, 7, 9]])

In [58]:
np.max(arr1,axis=0)

array([8, 7, 9])

In [59]:
np.min(arr1,axis=1)

array([1, 4, 7])