In [1]:
import numpy as np

In [35]:
arr = np.array([2,3,4,'Karan'])
arr

array(['2', '3', '4', 'Karan'], dtype='<U11')

In [6]:
a = [2,3,4,'Karan']
for i in a:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'str'>


In [7]:
arr.shape

(4,)

In [8]:
arr.ndim

1

In [10]:
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [11]:
arr.ndim

2

## How to pass dimension in creating an array. 

In [19]:
arr = np.array([1,2,3],ndmin=3)
arr

array([[[1, 2, 3]]])

## How to pass data type while creating an array. 

In [21]:
arr = np.array([1,2,3],dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [25]:
x = np.array([(1,2),(3,4)],dtype = [('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [32]:
type(x[0][0])

numpy.int16

In [36]:
for i in arr:
    print(i)

2
3
4
Karan


In [38]:
arr = np.array([2,3,4,5,6,7],dtype=np.int32)
arr

array([2, 3, 4, 5, 6, 7])

In [42]:
np.mat(np.array([2,3,4,5,6,7],dtype=np.int32))

matrix([[2, 3, 4, 5, 6, 7]])

Matrix is the sub class of an array. We can also convert matrix to numpy and numpy to matrix.

In [45]:
arr = np.mat('1 2; 3 4')
arr

matrix([[1, 2],
        [3, 4]])

## Numpy.asarray 

In [46]:
arr = np.asarray([2,3,4,5])
arr

array([2, 3, 4, 5])

In [47]:
type(arr)

numpy.ndarray

In [48]:
arr = np.asanyarray([2,3,4,5])
arr

array([2, 3, 4, 5])

In [49]:
type(arr)

numpy.ndarray

In [52]:
arr = np.array([[1,2,3,4,5,6,7,8,9]])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

asanyarray - This will convert into an array if original data is not in any format of array. But if it is in alredy in any of array format then asanyarray will not be able to convert it. 

In [53]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [54]:
b = np.array(arr,copy=True)
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [55]:
b[0] = 234

In [56]:
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Numpy.fromfunction 

In [1]:
np.fromfunction(lambda i,j: i==j,(3,3),dtype=int)

<IPython.core.display.Javascript object>

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [3]:
np.fromfunction(lambda i,j,k: i*j*k,(3,3,3),dtype=int)

<IPython.core.display.Javascript object>

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]],

       [[0, 0, 0],
        [0, 2, 4],
        [0, 4, 8]]])