In [2]:
import numpy as np

In [3]:
np.logspace(2,3,num=4,base=2,endpoint=False)

array([4.        , 4.75682846, 5.65685425, 6.72717132])

In [7]:
np.arange(0,16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.arange(0,16).reshape(-3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
np.arange(0,16).reshape((8,2,1))

array([[[ 0],
        [ 1]],

       [[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]],

       [[14],
        [15]]])

In [10]:
arr=np.arange(0,16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.diag(arr)

array([ 0,  5, 10, 15])

diag pick daiognal values from numpy array.We can also pass k= positive & negative values to fetch it.

In [12]:
ar2 =np.diag(arr,k=1)

In [13]:
ar2

array([ 1,  6, 11])

In [14]:
np.diag(np.diag(arr))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [15]:
np.diag(arr)

array([ 0,  5, 10, 15])

## Create a two dimensional array with the flattened input.

In [16]:
np.diagflat([[1,2],[3,4]],k=0)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [17]:
np.tri(3,5,k=2)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.tril([[1,2,3],[4,5,6],[7,8,9]],k=0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [19]:
np.triu([[1,2,3],[4,5,6],[7,8,9]],k=0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

# Random number generation 

In [20]:
np.random.rand(2,3) #2row and 3 columns

array([[0.45030285, 0.61413277, 0.29469212],
       [0.17710398, 0.54623965, 0.27356377]])

In [21]:
np.random.randn(1,10,2) #Going to generate data which is normally distributed.

array([[[-0.75593496,  1.30970019],
        [-0.72192167,  0.79240018],
        [ 0.07094148, -3.00242629],
        [ 0.57515489,  1.15008858],
        [ 0.72595427,  0.90645683],
        [-1.49859927,  0.84930239],
        [ 1.05651836, -1.38974989],
        [-1.03904558,  0.87436343],
        [ 1.60052223, -0.18031505],
        [ 0.39360315, -0.84539009]]])

In [22]:
np.random.randint(1,10)

6

In [23]:
np.random.randint(1,10,(4,5))

array([[4, 9, 4, 8, 1],
       [9, 5, 6, 1, 9],
       [8, 8, 9, 4, 4],
       [4, 6, 4, 1, 1]])

# Reshaping 

In [24]:
from numpy.random import randint as ri

In [26]:
np.random.rand(10)

array([0.33449808, 0.57016134, 0.40466801, 0.28878023, 0.69355659,
       0.42063762, 0.98438509, 0.75890561, 0.37805072, 0.42417872])

In [25]:
np.random.randint(1,10)

2

In [67]:
ri(1,10,(2,5))

array([[6, 2, 8, 5, 7],
       [2, 2, 9, 1, 2]])

In [71]:
a = ri(1,100,10)
a.sort()
a

array([13, 15, 26, 29, 65, 76, 85, 85, 98, 99])

In [76]:
arr = ri(1,100,25).reshape(5,5)
arr

array([[95, 13, 83, 25, 72],
       [48, 35, 91, 14, 14],
       [71, 23, 81, 90, 91],
       [67, 14, 21, 87, 29],
       [34, 44, 59, 34, 44]])

In [77]:
np.sort(arr,axis=1)

<IPython.core.display.Javascript object>

array([[13, 25, 72, 83, 95],
       [14, 14, 35, 48, 91],
       [23, 71, 81, 90, 91],
       [14, 21, 29, 67, 87],
       [34, 34, 44, 44, 59]])

In [78]:
np.sort(arr,axis=0)

<IPython.core.display.Javascript object>

array([[34, 13, 21, 14, 14],
       [48, 14, 59, 25, 29],
       [67, 23, 81, 34, 44],
       [71, 35, 83, 87, 72],
       [95, 44, 91, 90, 91]])

By default it use axis=1 i.e. column wise.

In [81]:
arr.max(axis=0)

array([95, 44, 91, 90, 91])

In [82]:
arr.max()

95

In [90]:
arr.argmax(axis=1) #Mention Index of largest values depend upon axis mention.

array([0, 2, 4, 3, 2], dtype=int64)

In [91]:
arr

array([[95, 13, 83, 25, 72],
       [48, 35, 91, 14, 14],
       [71, 23, 81, 90, 91],
       [67, 14, 21, 87, 29],
       [34, 44, 59, 34, 44]])

In [92]:
arr.argmax()

0

# Indexing & Slicing in Numpy arrays 

In [93]:
arr

array([[95, 13, 83, 25, 72],
       [48, 35, 91, 14, 14],
       [71, 23, 81, 90, 91],
       [67, 14, 21, 87, 29],
       [34, 44, 59, 34, 44]])

In [97]:
arr[0:,0:3]

array([[95, 13, 83],
       [48, 35, 91],
       [71, 23, 81],
       [67, 14, 21],
       [34, 44, 59]])

In [99]:
arr = ri(1,100,15).reshape(3,5)
arr

array([[39, 63, 24, 39, 95],
       [51, 50, 70, 77, 79],
       [95, 72, 54, 39,  6]])

In [106]:
arr[2,4]

6

# Subseting 

In [107]:
arr = ri(10,100,15).reshape(3,5)
arr

array([[92, 84, 34, 52, 77],
       [56, 82, 49, 81, 93],
       [25, 20, 61, 60, 91]])

In [113]:
ar2 = arr[arr>30]
ar2

array([92, 84, 34, 52, 77, 56, 82, 49, 81, 93, 61, 60, 91])

In [114]:
arr

array([[92, 84, 34, 52, 77],
       [56, 82, 49, 81, 93],
       [25, 20, 61, 60, 91]])

In [115]:
arr*ar2

ValueError: operands could not be broadcast together with shapes (3,5) (13,) 

In [116]:
arr@ar2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 13 is different from 5)

In [123]:
ar3=arr/1
ar3

array([[92., 84., 34., 52., 77.],
       [56., 82., 49., 81., 93.],
       [25., 20., 61., 60., 91.]])

In [121]:
arr

array([[92, 84, 34, 52, 77],
       [56, 82, 49, 81, 93],
       [25, 20, 61, 60, 91]])

In [124]:
arr+10

array([[102,  94,  44,  62,  87],
       [ 66,  92,  59,  91, 103],
       [ 35,  30,  71,  70, 101]])

# Broadcasting 

In [128]:
arr = np.zeros((4,4))+100
arr

<IPython.core.display.Javascript object>

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

# Array Math 

In [129]:
arr

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [131]:
np.sqrt(arr)

<IPython.core.display.Javascript object>

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [132]:
np.exp(arr)

<IPython.core.display.Javascript object>

array([[2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43],
       [2.68811714e+43, 2.68811714e+43, 2.68811714e+43, 2.68811714e+43]])

In [133]:
np.log10(arr)

<IPython.core.display.Javascript object>

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [136]:
arr2 = np.array(arr,copy=True)
arr2

<IPython.core.display.Javascript object>

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [137]:
np.fmod(arr,arr2)

<IPython.core.display.Javascript object>

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
a = np.linspace(1,1000)
a

<IPython.core.display.Javascript object>

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [143]:
a = np.arange(1,900.5,2)
a

<IPython.core.display.Javascript object>

array([  1.,   3.,   5.,   7.,   9.,  11.,  13.,  15.,  17.,  19.,  21.,
        23.,  25.,  27.,  29.,  31.,  33.,  35.,  37.,  39.,  41.,  43.,
        45.,  47.,  49.,  51.,  53.,  55.,  57.,  59.,  61.,  63.,  65.,
        67.,  69.,  71.,  73.,  75.,  77.,  79.,  81.,  83.,  85.,  87.,
        89.,  91.,  93.,  95.,  97.,  99., 101., 103., 105., 107., 109.,
       111., 113., 115., 117., 119., 121., 123., 125., 127., 129., 131.,
       133., 135., 137., 139., 141., 143., 145., 147., 149., 151., 153.,
       155., 157., 159., 161., 163., 165., 167., 169., 171., 173., 175.,
       177., 179., 181., 183., 185., 187., 189., 191., 193., 195., 197.,
       199., 201., 203., 205., 207., 209., 211., 213., 215., 217., 219.,
       221., 223., 225., 227., 229., 231., 233., 235., 237., 239., 241.,
       243., 245., 247., 249., 251., 253., 255., 257., 259., 261., 263.,
       265., 267., 269., 271., 273., 275., 277., 279., 281., 283., 285.,
       287., 289., 291., 293., 295., 297., 299., 30