In [1]:
import numpy as np

In [45]:
myarr = np.array([[2,3,4,6]],np.int8)
myarr

array([[2, 3, 4, 6]], dtype=int8)

In [46]:
myarr[0,0]

2

In [47]:
myarr.shape

(1, 4)

In [48]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 1

In [7]:
myarr

array([[2, 1, 4, 6]], dtype=int8)

# ***Creating Numpy Arrays - With Python Structure like List, Tuple etc.***

In [56]:
lstarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
lstarray
lstarray.dtype
lstarray.size

9

In [9]:
lstarray.shape

(3, 3)

In [10]:
lstarray.size

9

In [11]:
lstarray.shape

(3, 3)

In [12]:
lstarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Creating array with - Intrinsic Numpy arrays

In [13]:
zeroes = np.zeros((2,5))

In [14]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [79]:
rng = np.arange(1,15,2)
rng

array([ 1,  3,  5,  7,  9, 11, 13])

In [62]:
rng2 = np.arange((15))
rng2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
rng2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
rng

array([ 1,  3,  5,  7,  9, 11, 13])

In [65]:
lspace = np.linspace(1,50,6)

In [66]:
lspace

array([ 1. , 10.8, 20.6, 30.4, 40.2, 50. ])

In [21]:
#To create blank array, we can use


In [73]:
emp = np.empty((5,5))

In [76]:
emp

array([[2.00000000e+000, 1.60219306e-306, 2.44763557e-307,
        1.69119330e-306, 1.33514617e-307],
       [3.22651327e-307, 1.37962320e-306, 1.78019761e-306,
        3.11524091e-307, 1.60219035e-306],
       [6.23059386e-307, 6.23036978e-307, 1.24611674e-306,
        1.11258175e-306, 3.22651328e-307],
       [1.02359984e-306, 1.33511290e-306, 1.86921958e-306,
        6.23058368e-307, 1.11260348e-306],
       [1.37962049e-306, 2.22521238e-306, 1.24611470e-306,
        1.42410974e-306, 3.20558931e-317]])

In [75]:
emp[0,0] = 2

In [24]:
#Later on we can fill these values

In [25]:
emp = np.empty_like(myarr)

In [26]:
emp

array([[0, 0, 0, 0]], dtype=int8)

In [27]:
#emp_like will create empty array with relate to some other array which we have already created

In [28]:
 for i in myarr:
        print(i)

[2 1 4 6]


In [29]:
#To give a new shape to exisitng array 

In [30]:
arr2 = np.arange(10)

In [31]:
arr2.shape

(10,)

In [32]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
new_arr = arr2.ravel()

In [34]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
new_arr.shape

(10,)

In [51]:
myarr = np.array([[2,3,4,6]],np.int8)

In [52]:
for i in myarr:
    print(i)

[2 3 4 6]


In [83]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
a1.sum(axis=0)

array([12, 15, 18])

In [85]:
a1.sum(axis=1)

array([ 6, 15, 24])

In [87]:
a1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [88]:
for i in a1:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [89]:
for i in a1.flat:
    print(i)

1
2
3
4
5
6
7
8
9


In [93]:
 ar1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [94]:
ar2 = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [103]:
ar3 = ar1/ar2

In [104]:
ar3

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ],
       [0.4375    , 0.47058824, 0.5       ]])

In [105]:
 import sys

In [106]:
sys.getsizeof(1)

28

In [112]:
py_ar = [1,2,3]

In [113]:
np_ar = np.array(py_ar)

In [109]:
sys.getsizeof(1)*len(py_ar)

84

In [114]:
np_ar.itemsize * np_ar.size

12