In [1]:
import numpy as np

In [2]:
myarr = np.array([[2,3,4,6]],np.int8)

In [3]:
myarr[0,1]

3

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [6]:
myarr[0,1] = 1

In [7]:
myarr

array([[2, 1, 4, 6]], dtype=int8)

#Creating Numpy Arrays - With Python Structure like List, Tuple etc.

In [8]:
lstarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
lstarray.shape

(3, 3)

In [10]:
lstarray.size

9

In [11]:
lstarray.shape

(3, 3)

In [12]:
lstarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Creating array with - Intrinsic Numpy arrays

In [13]:
zeroes = np.zeros((2,5))

In [14]:
zeroes

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
rng = np.arange(1,15,2)

In [16]:
rng2 = np.arange((15))

In [17]:
rng2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
rng

array([ 1,  3,  5,  7,  9, 11, 13])

In [19]:
lspace = np.linspace(1,50,10)

In [20]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [21]:
#To create blank array, we can use


In [25]:
emp = np.empty((5,5))

In [26]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061074e-306, 1.89146896e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.24611674e-306, 1.29061821e-306],
       [6.23057349e-307, 2.22522597e-306, 1.06810268e-306,
        6.23052935e-307, 9.34600963e-307],
       [9.34608432e-307, 2.22522597e-306, 1.33511969e-306,
        8.34426039e-308, 2.10081501e-312]])

In [27]:
#Later on we can fill these values

In [29]:
emp = np.empty_like(myarr)

In [30]:
emp

array([[0, 0, 0, 0]], dtype=int8)

In [31]:
#emp_like will create empty array with relate to some other array which we have already created

In [32]:
 for i in myarr:
        print(i)

[2 1 4 6]


In [33]:
#To give a new shape to exisitng array 

In [39]:
arr2 = np.arange(10)

In [40]:
arr2.shape

(10,)

In [41]:
arr2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [44]:
new_arr = arr2.ravel()

In [45]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
new_arr.shape

(10,)